//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryForTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgSource
    {
        public int Id { get; set; }
        public string Scr { get; set; }
        public int Fk_PageUrls_Id { get; set; }
    
        public virtual PageUrl PageUrl { get; set; }
    }
}
