//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryForTask
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FistTaskEntities : DbContext
    {
        public FistTaskEntities()
            : base("name=FistTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CssLink> CssLink { get; set; }
        public virtual DbSet<ExternalUrl> ExternalUrl { get; set; }
        public virtual DbSet<ImgSource> ImgSource { get; set; }
        public virtual DbSet<InternalUrl> InternalUrl { get; set; }
        public virtual DbSet<PageUrl> PageUrl { get; set; }
    }
}
