//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryForTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageUrl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageUrl()
        {
            this.CssLink = new HashSet<CssLink>();
            this.ExternalUrl = new HashSet<ExternalUrl>();
            this.ImgSource = new HashSet<ImgSource>();
            this.InternalUrl = new HashSet<InternalUrl>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> LoadTime { get; set; }
        public Nullable<int> HtmlSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssLink> CssLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUrl> ExternalUrl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgSource> ImgSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalUrl> InternalUrl { get; set; }
    }
}
