//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageUrls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageUrls()
        {
            this.CssLinks = new HashSet<CssLinks>();
            this.ExternalUrls = new HashSet<ExternalUrls>();
            this.ImgSources = new HashSet<ImgSources>();
            this.InternalUrls = new HashSet<InternalUrls>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> LoadTime { get; set; }
        public Nullable<int> HtmlSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssLinks> CssLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUrls> ExternalUrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgSources> ImgSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalUrls> InternalUrls { get; set; }
    }
}
