//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssLinks
    {
        public int Id { get; set; }
        public string Css { get; set; }
        public int Fk_PageUrls_Id { get; set; }
    
        public virtual PageUrls PageUrls { get; set; }
    }
}
