//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FistTaskEntities : DbContext
    {
        public FistTaskEntities()
            : base("name=FistTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CssLinks> CssLinks { get; set; }
        public virtual DbSet<ExternalUrls> ExternalUrls { get; set; }
        public virtual DbSet<Hosts> Hosts { get; set; }
        public virtual DbSet<ImgSources> ImgSources { get; set; }
        public virtual DbSet<InternalUrls> InternalUrls { get; set; }
        public virtual DbSet<PageUrls> PageUrls { get; set; }
    }
}
